# Generated by Django 3.1.1 on 2020-09-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], default=None, max_length=6, null=True)),
                ('rate', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
