# Generated by Django 3.1.1 on 2020-09-28 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provider', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='contacts',
            field=models.ManyToManyField(to='user.Contact'),
        ),
        migrations.AddField(
            model_name='provider',
            name='services',
            field=models.ManyToManyField(to='service.Service'),
        ),
        migrations.AddField(
            model_name='provider',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
