# Generated by Django 3.1.1 on 2020-09-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'm'), ('tuesday', 't'), ('wednesday', 'w'), ('thursday', 'th'), ('friday', 'f'), ('saturday', 's'), ('sunday', 'su')], default=None, max_length=20)),
                ('begin', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('is_break', models.BooleanField(default=False)),
            ],
        ),
    ]
