# Generated by Django 3.1.1 on 2020-10-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_auto_20200928_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='service',
        ),
        migrations.AddField(
            model_name='availability',
            name='is_working',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
